/**
 *
 *  RestfulDishCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulDishCtrl.h"
#include <string>

void RestfulDishCtrl::getOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Dish::PrimaryKeyType &&id)
{
    RestfulDishCtrlBase::getOne(req, std::move(callback), std::move(id));
}

void RestfulDishCtrl::updateOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Dish::PrimaryKeyType &&id)
{
    RestfulDishCtrlBase::updateOne(req, std::move(callback), std::move(id));
}

void RestfulDishCtrl::deleteOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Dish::PrimaryKeyType &&id)
{
    RestfulDishCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulDishCtrl::get(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulDishCtrlBase::get(req, std::move(callback));
}

void RestfulDishCtrl::getHotDishes(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulDishCtrlBase::getHotDishes(req, std::move(callback));
}

void RestfulDishCtrl::create(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulDishCtrlBase::create(req, std::move(callback));
}
