/**
 *
 *  RestfulOrderTableCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulOrderTableCtrlBase.h"

#include "OrderTable.h"
using namespace drogon;
using namespace drogon_model::saas_restaurant;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the order_table table.
 */

class RestfulOrderTableCtrl : public drogon::HttpController<RestfulOrderTableCtrl>, public RestfulOrderTableCtrlBase
{
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulOrderTableCtrl::getOne, "/api/ordertable/{1}", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulOrderTableCtrl::updateOne, "/api/ordertable/{1}", Put, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulOrderTableCtrl::deleteOne, "/api/ordertable/{1}", Delete, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulOrderTableCtrl::get, "/api/ordertable", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulOrderTableCtrl::create, "/api/ordertable", Post, Options, "AuthFilter");
  // ADD_METHOD_TO(RestfulOrderTableCtrl::update,"/api/ordertable",Put,Options);
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback,
              OrderTable::PrimaryKeyType &&id);
  void updateOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 OrderTable::PrimaryKeyType &&id);
  void deleteOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 OrderTable::PrimaryKeyType &&id);
  void get(const HttpRequestPtr &req,
           std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
