/**
 *
 *  RestfulMemberCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulMemberCtrl.h"
#include <string>


void RestfulMemberCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Member::PrimaryKeyType &&id)
{
    RestfulMemberCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulMemberCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Member::PrimaryKeyType &&id)
{
    RestfulMemberCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulMemberCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Member::PrimaryKeyType &&id)
{
    RestfulMemberCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulMemberCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMemberCtrlBase::get(req, std::move(callback));
}

void RestfulMemberCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMemberCtrlBase::create(req, std::move(callback));
}
