/**
 *
 *  RestfulPermissionCategoryCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulPermissionCategoryCtrl.h"
#include <string>


void RestfulPermissionCategoryCtrl::getOne(const HttpRequestPtr &req,
                                           std::function<void(const HttpResponsePtr &)> &&callback,
                                           PermissionCategory::PrimaryKeyType &&id)
{
    RestfulPermissionCategoryCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulPermissionCategoryCtrl::updateOne(const HttpRequestPtr &req,
                                              std::function<void(const HttpResponsePtr &)> &&callback,
                                              PermissionCategory::PrimaryKeyType &&id)
{
    RestfulPermissionCategoryCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulPermissionCategoryCtrl::deleteOne(const HttpRequestPtr &req,
                                              std::function<void(const HttpResponsePtr &)> &&callback,
                                              PermissionCategory::PrimaryKeyType &&id)
{
    RestfulPermissionCategoryCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulPermissionCategoryCtrl::get(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulPermissionCategoryCtrlBase::get(req, std::move(callback));
}

void RestfulPermissionCategoryCtrl::create(const HttpRequestPtr &req,
                                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulPermissionCategoryCtrlBase::create(req, std::move(callback));
}
