/**
 *
 *  RestfulBranchCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulBranchCtrlBase.h"

#include "Branch.h"
using namespace drogon;
using namespace drogon_model::saas_restaurant;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the branch table.
 */

class RestfulBranchCtrl : public drogon::HttpController<RestfulBranchCtrl>, public RestfulBranchCtrlBase
{
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulBranchCtrl::getOne, "/api/branch/{1}", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulBranchCtrl::updateOne, "/api/branch/{1}", Put, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulBranchCtrl::deleteOne, "/api/branch/{1}", Delete, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulBranchCtrl::get, "/api/branch", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulBranchCtrl::create, "/api/branch", Post, Options, "AuthFilter");
  // ADD_METHOD_TO(RestfulBranchCtrl::update,"/api/branch",Put,Options,"AuthFilter");
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback,
              Branch::PrimaryKeyType &&id);
  void updateOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 Branch::PrimaryKeyType &&id);
  void deleteOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 Branch::PrimaryKeyType &&id);
  void get(const HttpRequestPtr &req,
           std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
