/**
 *
 *  RestfulBranchCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulBranchCtrl.h"
#include <string>


void RestfulBranchCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Branch::PrimaryKeyType &&id)
{
    RestfulBranchCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulBranchCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Branch::PrimaryKeyType &&id)
{
    RestfulBranchCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulBranchCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Branch::PrimaryKeyType &&id)
{
    RestfulBranchCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulBranchCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulBranchCtrlBase::get(req, std::move(callback));
}

void RestfulBranchCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulBranchCtrlBase::create(req, std::move(callback));
}
