/**
 *
 *  RestfulInventoryCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulInventoryCtrl.h"
#include <string>


void RestfulInventoryCtrl::getOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Inventory::PrimaryKeyType &&id)
{
    RestfulInventoryCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulInventoryCtrl::updateOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Inventory::PrimaryKeyType &&id)
{
    RestfulInventoryCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulInventoryCtrl::deleteOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Inventory::PrimaryKeyType &&id)
{
    RestfulInventoryCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulInventoryCtrl::get(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulInventoryCtrlBase::get(req, std::move(callback));
}

void RestfulInventoryCtrl::create(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulInventoryCtrlBase::create(req, std::move(callback));
}
