/**
 *
 *  RestfulTenantCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulTenantCtrl.h"
#include <string>

void RestfulTenantCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Tenant::PrimaryKeyType &&id)
{
    RestfulTenantCtrlBase::getOne(req, std::move(callback), std::move(id));
}

void RestfulTenantCtrl::getToken(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Tenant::PrimaryKeyType &&id)
{
    RestfulTenantCtrlBase::getToken(req, std::move(callback), std::move(id));
}

void RestfulTenantCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Tenant::PrimaryKeyType &&id)
{
    RestfulTenantCtrlBase::updateOne(req, std::move(callback), std::move(id));
}

void RestfulTenantCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Tenant::PrimaryKeyType &&id)
{
    RestfulTenantCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulTenantCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulTenantCtrlBase::get(req, std::move(callback));
}

void RestfulTenantCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulTenantCtrlBase::create(req, std::move(callback));
}
