/**
 *
 *  RestfulMarketingCampaignCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulMarketingCampaignCtrlBase.h"

#include "MarketingCampaign.h"
using namespace drogon;
using namespace drogon_model::saas_restaurant;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the marketing_campaign table.
 */

class RestfulMarketingCampaignCtrl : public drogon::HttpController<RestfulMarketingCampaignCtrl>, public RestfulMarketingCampaignCtrlBase
{
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulMarketingCampaignCtrl::getOne, "/api/marketingcampaign/{1}", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMarketingCampaignCtrl::updateOne, "/api/marketingcampaign/{1}", Put, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMarketingCampaignCtrl::deleteOne, "/api/marketingcampaign/{1}", Delete, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMarketingCampaignCtrl::get, "/api/marketingcampaign", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMarketingCampaignCtrl::create, "/api/marketingcampaign", Post, Options, "AuthFilter");
  // ADD_METHOD_TO(RestfulMarketingCampaignCtrl::update,"/api/marketingcampaign",Put,Options,"AuthFilter");
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback,
              MarketingCampaign::PrimaryKeyType &&id);
  void updateOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 MarketingCampaign::PrimaryKeyType &&id);
  void deleteOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 MarketingCampaign::PrimaryKeyType &&id);
  void get(const HttpRequestPtr &req,
           std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
