/**
 *
 *  RestfulUserRoleCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUserRoleCtrlBase.h"

#include "UserRole.h"
using namespace drogon;
using namespace drogon_model::saas_restaurant;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the user_role table.
 */

class RestfulUserRoleCtrl : public drogon::HttpController<RestfulUserRoleCtrl>, public RestfulUserRoleCtrlBase
{
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulUserRoleCtrl::getOne, "/api/userrole/{1}", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulUserRoleCtrl::updateOne, "/api/userrole/{1}", Put, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulUserRoleCtrl::deleteOne, "/api/userrole/{1}", Delete, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulUserRoleCtrl::get, "/api/userrole", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulUserRoleCtrl::create, "/api/userrole", Post, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulUserRoleCtrl::getRolesByUserId, "/api/userrole/user/{1}", Get, Options, "AuthFilter");
  // ADD_METHOD_TO(RestfulUserRoleCtrl::update,"/api/userrole",Put,Options);
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback,
              UserRole::PrimaryKeyType &&id);
  void getRolesByUserId(const HttpRequestPtr &req,
                        std::function<void(const HttpResponsePtr &)> &&callback,
                        std::string &&id);
  void updateOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 UserRole::PrimaryKeyType &&id);
  void deleteOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 UserRole::PrimaryKeyType &&id);
  void get(const HttpRequestPtr &req,
           std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
