/**
 *
 *  RestfulRolePermissionCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulRolePermissionCtrl.h"
#include <string>


void RestfulRolePermissionCtrl::getOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       RolePermission::PrimaryKeyType &&id)
{
    RestfulRolePermissionCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulRolePermissionCtrl::updateOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          RolePermission::PrimaryKeyType &&id)
{
    RestfulRolePermissionCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulRolePermissionCtrl::deleteOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          RolePermission::PrimaryKeyType &&id)
{
    RestfulRolePermissionCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulRolePermissionCtrl::get(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRolePermissionCtrlBase::get(req, std::move(callback));
}

void RestfulRolePermissionCtrl::create(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRolePermissionCtrlBase::create(req, std::move(callback));
}
