/**
 *
 *  RestfulUserRoleCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUserRoleCtrl.h"
#include <string>

void RestfulUserRoleCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 UserRole::PrimaryKeyType &&id)
{
    RestfulUserRoleCtrlBase::getOne(req, std::move(callback), std::move(id));
}

void RestfulUserRoleCtrl::getRolesByUserId(const HttpRequestPtr &req,
                                           std::function<void(const HttpResponsePtr &)> &&callback,
                                           std::string &&id)
{
    RestfulUserRoleCtrlBase::getRolesByUserId(req, std::move(callback), std::move(id));
}

void RestfulUserRoleCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    UserRole::PrimaryKeyType &&id)
{
    RestfulUserRoleCtrlBase::updateOne(req, std::move(callback), std::move(id));
}

void RestfulUserRoleCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    UserRole::PrimaryKeyType &&id)
{
    RestfulUserRoleCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulUserRoleCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserRoleCtrlBase::get(req, std::move(callback));
}

void RestfulUserRoleCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserRoleCtrlBase::create(req, std::move(callback));
}
