/**
 *
 *  RestfulMenuCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulMenuCtrlBase.h"

#include "Menu.h"
using namespace drogon;
using namespace drogon_model::saas_restaurant;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the menu table.
 */

class RestfulMenuCtrl : public drogon::HttpController<RestfulMenuCtrl>, public RestfulMenuCtrlBase
{
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulMenuCtrl::getOne, "/api/menu/{1}", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMenuCtrl::updateOne, "/api/menu/{1}", Put, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMenuCtrl::deleteOne, "/api/menu/{1}", Delete, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMenuCtrl::get, "/api/menu", Get, Options, "AuthFilter");
  ADD_METHOD_TO(RestfulMenuCtrl::create, "/api/menu", Post, Options, "AuthFilter");
  // ADD_METHOD_TO(RestfulMenuCtrl::update,"/api/menu",Put,Options,"AuthFilter");
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback,
              Menu::PrimaryKeyType &&id);
  void updateOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 Menu::PrimaryKeyType &&id);
  void deleteOne(const HttpRequestPtr &req,
                 std::function<void(const HttpResponsePtr &)> &&callback,
                 Menu::PrimaryKeyType &&id);
  void get(const HttpRequestPtr &req,
           std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &req,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
