/**
 *
 *  Member.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace saas_restaurant
{
class ConsumptionRecord;
class MemberLevel;
class Tenant;
class User;

class Member
{
  public:
    struct Cols
    {
        static const std::string _member_id;
        static const std::string _user_id;
        static const std::string _tenant_id;
        static const std::string _level_id;
        static const std::string _member_no;
        static const std::string _points;
        static const std::string _total_points;
        static const std::string _total_spent;
        static const std::string _expire_date;
        static const std::string _status;
        static const std::string _created_at;
        static const std::string _updated_at;
        static const std::string _is_deleted;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = uint32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Member(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Member(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Member(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Member() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column member_id  */
    ///Get the value of the column member_id, returns the default value if the column is null
    const uint32_t &getValueOfMemberId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getMemberId() const noexcept;
    ///Set the value of the column member_id
    void setMemberId(const uint32_t &pMemberId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const uint32_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const uint32_t &pUserId) noexcept;
    void setUserIdToNull() noexcept;

    /**  For column tenant_id  */
    ///Get the value of the column tenant_id, returns the default value if the column is null
    const uint32_t &getValueOfTenantId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getTenantId() const noexcept;
    ///Set the value of the column tenant_id
    void setTenantId(const uint32_t &pTenantId) noexcept;
    void setTenantIdToNull() noexcept;

    /**  For column level_id  */
    ///Get the value of the column level_id, returns the default value if the column is null
    const uint32_t &getValueOfLevelId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getLevelId() const noexcept;
    ///Set the value of the column level_id
    void setLevelId(const uint32_t &pLevelId) noexcept;
    void setLevelIdToNull() noexcept;

    /**  For column member_no  */
    ///Get the value of the column member_no, returns the default value if the column is null
    const std::string &getValueOfMemberNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMemberNo() const noexcept;
    ///Set the value of the column member_no
    void setMemberNo(const std::string &pMemberNo) noexcept;
    void setMemberNo(std::string &&pMemberNo) noexcept;
    void setMemberNoToNull() noexcept;

    /**  For column points  */
    ///Get the value of the column points, returns the default value if the column is null
    const uint32_t &getValueOfPoints() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getPoints() const noexcept;
    ///Set the value of the column points
    void setPoints(const uint32_t &pPoints) noexcept;
    void setPointsToNull() noexcept;

    /**  For column total_points  */
    ///Get the value of the column total_points, returns the default value if the column is null
    const uint32_t &getValueOfTotalPoints() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getTotalPoints() const noexcept;
    ///Set the value of the column total_points
    void setTotalPoints(const uint32_t &pTotalPoints) noexcept;
    void setTotalPointsToNull() noexcept;

    /**  For column total_spent  */
    ///Get the value of the column total_spent, returns the default value if the column is null
    const std::string &getValueOfTotalSpent() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTotalSpent() const noexcept;
    ///Set the value of the column total_spent
    void setTotalSpent(const std::string &pTotalSpent) noexcept;
    void setTotalSpent(std::string &&pTotalSpent) noexcept;
    void setTotalSpentToNull() noexcept;

    /**  For column expire_date  */
    ///Get the value of the column expire_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfExpireDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getExpireDate() const noexcept;
    ///Set the value of the column expire_date
    void setExpireDate(const ::trantor::Date &pExpireDate) noexcept;
    void setExpireDateToNull() noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const std::string &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const std::string &pStatus) noexcept;
    void setStatus(std::string &&pStatus) noexcept;
    void setStatusToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;

    /**  For column is_deleted  */
    ///Get the value of the column is_deleted, returns the default value if the column is null
    const int8_t &getValueOfIsDeleted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getIsDeleted() const noexcept;
    ///Set the value of the column is_deleted
    void setIsDeleted(const int8_t &pIsDeleted) noexcept;
    void setIsDeletedToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    User getUser(const drogon::orm::DbClientPtr &clientPtr) const;
    void getUser(const drogon::orm::DbClientPtr &clientPtr,
                 const std::function<void(User)> &rcb,
                 const drogon::orm::ExceptionCallback &ecb) const;
    Tenant getTenant(const drogon::orm::DbClientPtr &clientPtr) const;
    void getTenant(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Tenant)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    MemberLevel getMemberLevel(const drogon::orm::DbClientPtr &clientPtr) const;
    void getMemberLevel(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(MemberLevel)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<ConsumptionRecord> getConsumption_records(const drogon::orm::DbClientPtr &clientPtr) const;
    void getConsumption_records(const drogon::orm::DbClientPtr &clientPtr,
                                const std::function<void(std::vector<ConsumptionRecord>)> &rcb,
                                const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Member>;
    friend drogon::orm::BaseBuilder<Member, true, true>;
    friend drogon::orm::BaseBuilder<Member, true, false>;
    friend drogon::orm::BaseBuilder<Member, false, true>;
    friend drogon::orm::BaseBuilder<Member, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Member>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint32_t> memberId_;
    std::shared_ptr<uint32_t> userId_;
    std::shared_ptr<uint32_t> tenantId_;
    std::shared_ptr<uint32_t> levelId_;
    std::shared_ptr<std::string> memberNo_;
    std::shared_ptr<uint32_t> points_;
    std::shared_ptr<uint32_t> totalPoints_;
    std::shared_ptr<std::string> totalSpent_;
    std::shared_ptr<::trantor::Date> expireDate_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    std::shared_ptr<int8_t> isDeleted_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where member_id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where member_id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "member_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "tenant_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "level_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "member_no,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "points,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "total_points,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "total_spent,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "expire_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "status,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        if(dirtyFlag_[11])
        {
            sql += "updated_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "is_deleted,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[12])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace saas_restaurant
} // namespace drogon_model
