/**
 *
 *  Menu.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace saas_restaurant
{
class Menu;
class Permission;
class Tenant;

class Menu
{
  public:
    struct Cols
    {
        static const std::string _menu_id;
        static const std::string _tenant_id;
        static const std::string _parent_id;
        static const std::string _permission_id;
        static const std::string _menu_name;
        static const std::string _menu_type;
        static const std::string _path;
        static const std::string _icon;
        static const std::string _sort;
        static const std::string _is_visible;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = uint32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Menu(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Menu(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Menu(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Menu() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column menu_id  */
    ///Get the value of the column menu_id, returns the default value if the column is null
    const uint32_t &getValueOfMenuId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getMenuId() const noexcept;
    ///Set the value of the column menu_id
    void setMenuId(const uint32_t &pMenuId) noexcept;

    /**  For column tenant_id  */
    ///Get the value of the column tenant_id, returns the default value if the column is null
    const uint32_t &getValueOfTenantId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getTenantId() const noexcept;
    ///Set the value of the column tenant_id
    void setTenantId(const uint32_t &pTenantId) noexcept;
    void setTenantIdToNull() noexcept;

    /**  For column parent_id  */
    ///Get the value of the column parent_id, returns the default value if the column is null
    const uint32_t &getValueOfParentId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getParentId() const noexcept;
    ///Set the value of the column parent_id
    void setParentId(const uint32_t &pParentId) noexcept;
    void setParentIdToNull() noexcept;

    /**  For column permission_id  */
    ///Get the value of the column permission_id, returns the default value if the column is null
    const uint32_t &getValueOfPermissionId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getPermissionId() const noexcept;
    ///Set the value of the column permission_id
    void setPermissionId(const uint32_t &pPermissionId) noexcept;
    void setPermissionIdToNull() noexcept;

    /**  For column menu_name  */
    ///Get the value of the column menu_name, returns the default value if the column is null
    const std::string &getValueOfMenuName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMenuName() const noexcept;
    ///Set the value of the column menu_name
    void setMenuName(const std::string &pMenuName) noexcept;
    void setMenuName(std::string &&pMenuName) noexcept;
    void setMenuNameToNull() noexcept;

    /**  For column menu_type  */
    ///Get the value of the column menu_type, returns the default value if the column is null
    const std::string &getValueOfMenuType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMenuType() const noexcept;
    ///Set the value of the column menu_type
    void setMenuType(const std::string &pMenuType) noexcept;
    void setMenuType(std::string &&pMenuType) noexcept;
    void setMenuTypeToNull() noexcept;

    /**  For column path  */
    ///Get the value of the column path, returns the default value if the column is null
    const std::string &getValueOfPath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPath() const noexcept;
    ///Set the value of the column path
    void setPath(const std::string &pPath) noexcept;
    void setPath(std::string &&pPath) noexcept;
    void setPathToNull() noexcept;

    /**  For column icon  */
    ///Get the value of the column icon, returns the default value if the column is null
    const std::string &getValueOfIcon() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIcon() const noexcept;
    ///Set the value of the column icon
    void setIcon(const std::string &pIcon) noexcept;
    void setIcon(std::string &&pIcon) noexcept;
    void setIconToNull() noexcept;

    /**  For column sort  */
    ///Get the value of the column sort, returns the default value if the column is null
    const uint32_t &getValueOfSort() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getSort() const noexcept;
    ///Set the value of the column sort
    void setSort(const uint32_t &pSort) noexcept;
    void setSortToNull() noexcept;

    /**  For column is_visible  */
    ///Get the value of the column is_visible, returns the default value if the column is null
    const uint8_t &getValueOfIsVisible() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint8_t> &getIsVisible() const noexcept;
    ///Set the value of the column is_visible
    void setIsVisible(const uint8_t &pIsVisible) noexcept;
    void setIsVisibleToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 12;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Tenant getTenant(const drogon::orm::DbClientPtr &clientPtr) const;
    void getTenant(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Tenant)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Menu> getMenus(const drogon::orm::DbClientPtr &clientPtr) const;
    void getMenus(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(std::vector<Menu>)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    Menu getParent(const drogon::orm::DbClientPtr &clientPtr) const;
    void getParent(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Menu)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Permission> getPermissions(const drogon::orm::DbClientPtr &clientPtr) const;
    void getPermissions(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(std::vector<Permission>)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Menu>;
    friend drogon::orm::BaseBuilder<Menu, true, true>;
    friend drogon::orm::BaseBuilder<Menu, true, false>;
    friend drogon::orm::BaseBuilder<Menu, false, true>;
    friend drogon::orm::BaseBuilder<Menu, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Menu>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint32_t> menuId_;
    std::shared_ptr<uint32_t> tenantId_;
    std::shared_ptr<uint32_t> parentId_;
    std::shared_ptr<uint32_t> permissionId_;
    std::shared_ptr<std::string> menuName_;
    std::shared_ptr<std::string> menuType_;
    std::shared_ptr<std::string> path_;
    std::shared_ptr<std::string> icon_;
    std::shared_ptr<uint32_t> sort_;
    std::shared_ptr<uint8_t> isVisible_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[12]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where menu_id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where menu_id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "menu_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "tenant_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "parent_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "permission_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "menu_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "menu_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "path,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "icon,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "sort,";
            ++parametersCount;
        }
        sql += "is_visible,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[11])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace saas_restaurant
} // namespace drogon_model
